### ISSUE TITLE
Build Fail due to problems with activity_profile 

### ISSUE THREAD

**Issue by Sidney4** [MrRynard/Fox-Holdings-Hospitality#6]
Some code has not been added that is needed here. There are also a few syntax errors.

**Comment by MrRynard** [comment]
Can you post what code was missing and what the syntax errors were?

**Comment by Sidney4** [comment]
Solution:
Add the following to the ScrollView tag:
xmlns:app="http://schemas.android.com/apk/res-auto"

Search for this tag: <android.support.v7.widget.CardView
at the closing tag add a '/' before >
This will make it look like this:

<android.support.v7.widget.CardView
        android:id="@+id/btnLogin"
        android:clickable="true"
        android:layout_width="300dp"
        android:layout_height="50dp"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="109dp"
        android:elevation="10dp"
        app:cardBackgroundColor="@color/colorAccent"
        app:cardCornerRadius="25dp"
        android:onClick="btnLoginClicked"/>

Lastly: Add a closing tag for Relative layout.
The Last 3 closing tags of the file should be:

 </RelativeLayout>
    </LinearLayout>
</ScrollView>

**Comment by Sidney4** [comment]
Lastly do not use toolbar in MainActivity remove this code:

Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

**Comment by Sidney4** [comment]
Ok again remove that same code from MenuItems.java
